### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by IKUH2** [IKUH2/furima_-28750-#10]
https://furima-28750.herokuapp.com/

Basic認証のIDとパスワード:admin  9456
購入用　123@abc.com 123abc
販売用　321@abc.com 321abc
購入用カードの番号・期限・セキュリティコード:4242424242424242 12/24 123

**Comment by mo1015** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
**○URLにアクセスすると、はじめにログイン画面が出てきてしまう**
**トップページにアクセスできるようにしましょう、また、Basic認証を実装しましょう！**
<img width="1361" alt="スクリーンショット 2020-09-12 10 11 54" src="https://user-images.githubusercontent.com/62644781/92983828-c305a480-f4e0-11ea-8985-34d26c24a299.png">



修正でき次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by IKUH2** [comment]
指示通り修正しました！レビューお願いします！

**Comment by mutorisa** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**[修正依頼箇所]**
**○Isuueに記載してあるカード情報を使用しても商品を購入することができない状態です。正常に商品を購入できるようにしましょう。**

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by IKUH2** [comment]
色々修正しましたので、レビューお願いします！

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、前回の指摘箇所の修正が確認できなかったため、再度本番環境で正常に動作するか確認お願いします！

[修正依頼箇所]
**○Isuueに記載してあるカード情報を使用しても商品を購入することができない状態です。正常に商品を購入できるようにしましょう。**

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by IKUH2** [comment]
webpacker再起動しました！レビューお願いします！

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします**。
